### ISSUE TITLE
Problem with === operator when comparing to SortType.'ASC' and 'DESC'

### ISSUE THREAD

**Issue by KrzysiekT** [darekf77/ng2-rest#2]
Hello, we have a problem with === operator, when building on npm we're receiving such msg:

ng2-rest/src/mock-auto-backend.class.ts:141:27 
Operator '===' cannot be applied to types 'SortType.'ASC'' and 'SortType.'DESC''.

node v5.6.0
npm v3.6.0

**Comment by darekf77** [comment]
Just change in your **package.json** typescript beta to 
`"typescript": "2.0.0"`
