### ISSUE TITLE
Cannot find name 'require'.

### ISSUE THREAD

**Issue by impavidum** [darekf77/ng2-rest#5]
I am getting the following error upon installing the npm package. I am using ionic 2. 

typescript: node_modules/ng2-rest/src/mock-backend.ts, line: 1 
            Cannot find name 'require'. 

       L1:  const faker = require('faker');
       L2:  import { Http } from './http';

**Comment by impavidum** [comment]
perhaps const should be replaced with import here..

**Comment by darekf77** [comment]
should be ok in new version 5.0.30
